version: "3.8"

services:
  app:
    image: task-organizer:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_USER: postgres
      DB_PASSWORD: root
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: task_organizer_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: