spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_organizer
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt_secret_key: ZRwnCyyLJyj9vYNOzcSWl9lZH1nxKxXjmK4Sj6PhyvJ4nloNtBM7llutlHjuy5x9
allowed:
  origins: http://localhost:8080